export {default as Login} from './pages/Login/Login.tsx'
export { default as SignUp } from './pages/Signup/Signup.tsx'
export {default as Home} from './pages/Home/Home.jsx'
export {default as ViewProduct } from './pages/ViewProduct/ViewProduct.tsx'
export {default as Forgotpassword} from './pages/Forgotpassword/Forgotpassword.tsx'